### ISSUE TITLE
Limit number of "large" objects the player may hold

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#102]
The player may hold any number of the "heavy" objects (e.g. holding both a chair from the lobby west and the large potted plant from the hallway)

I know this was a feature we talked about including before, but I am unsure if this was left out intentionally

**Comment by pahp** [comment]
I do think we should implement this somehow -- seems weird if you can carry
a heavy chair and a potted plant at the same time.
