### ISSUE TITLE
Do we want rooms to give score upon entry?

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#117]
Office 6 (glass wall room) had the scored attribute, meaning when you entered the room you received a score increase. Is this something that we want to have happen in other rooms?

This is in addition to objects already giving you a score increase.

**Comment by Saturn-99** [comment]
It appears the bathroom also is considered scored, oddly enough

**Comment by spacehobo** [comment]
It's traditional to give a smaller score boost for entering an important room, as a hint to the player that they're on the right track.
