### ISSUE TITLE
unify description of paper printout

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#122]
The printout of Titor's schematics is great! However, in some places there are vestiges of the old puzzle, for example:

```
[X] Uploaded John Titor's schematics.
```

and

```
The screen shows upload progress as your exfiltration script runs.
```

I haven't looked at the code yet, so I'm not sure if the exfiltration script eventually completes, but if it never completes, I think the message should be removed. If it completes after, say, n turns, then maybe the printout shouldn't appear in the office until after that number of turns. In the latter case, it could say "the printer is still printing the documents you requested" or something like that.

**Comment by Saturn-99** [comment]
Nope! Those were unintended, I will fix these momentarily!

**Comment by Saturn-99** [comment]
Text slightly tweaked, issue should be fixed.
