### ISSUE TITLE
Allow use verb to plunger tiles

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#126]
![image](https://github.com/UMDLARS/one_night_in_sf/assets/116676184/1826ff32-2239-471f-9966-2fa2c973f7ee)

**Comment by pahp** [comment]
Use should also work with phillips screwdriver (same error trying to "use screwdriver on screws")

**Comment by spacehobo** [comment]
This is a duplicate of #143
