### ISSUE TITLE
USB disappears when inserted into Len's computer

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#129]
When you insert the USB stick into Len's computer, the USB stick disappears because it is now "in" Len's computer. However, Len's computer is not a container, so the stick cannot be taken back out. The stick is automagically returned when you power on the computer and steal the documents.

Possible solutions include 
* making the computer a container that is open so that you can see its contents, but it may be confusing if the computer says it is "open". It also doesn't make sense that the computer could be closed, so there'd be some hacking to do with that solution.
* changing the description of the computer depending on the USB status and adding conditional descriptions and a take/remove action to get it back.

**Comment by Saturn-99** [comment]
This issue has already been solved without closing this issue.
