### ISSUE TITLE
make Office3 door move/fall/open automatically once hinges removed

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#131]
![image](https://github.com/UMDLARS/one_night_in_sf/assets/15266857/5d17c8a5-c77c-40b4-9b45-742ace6bf532)

Right now the door has to manually be moved and still says that it is locked (which is technically true).

Maybe have the door fall over or just have you move the door, similar to how the USB stick works.

**Comment by spacehobo** [comment]
I know this is somewhat irrelevant, but is this puzzle why the `move` verb was implemented the way it was?  Would it be cleaner just to hook that functionality to the `push` verb?
