### ISSUE TITLE
Give some direct instructions in the begining on what actions they might want to do first

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#139]
During the intro text maybe include direction instructions, particularly to look in inventory and examine task list.

**Comment by Saturn-99** [comment]
Maybe have a few tutorial rooms even

**Comment by pahp** [comment]
Hmm... a tutorial room, that's a great idea, since most of our players will likely never have played text adventures before. Maybe the Waiting Room or the Receptionist's Area would be good? Especially if completing the tutorial resulted in you having the loose brass key?

**Comment by spacehobo** [comment]
I think a lift could make a good one-room tutorial.  Lead them into the beginning of the game after showing them how to use the verbs we give them.  Then we may not need to lean so hard on the `use` verb.

**Comment by pahp** [comment]
@Saturn-99 -- Let's split this issue... the instructions need to be clearer, including explaining the checklist, etc. 

Whether to do a tutorial room or not is a second issue.
