### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#140]
During my tests of watching people play, testers very quickly got lost

One attempted to make a map for herself, however it got too hard for her to keep track of and quickly got lost. I don't want to discount the idea of telling the students to maybe make a map but this seems a bit out of the purview of what we're looking to teach.

**Comment by pahp** [comment]
One of things that @Saturn-99 and I discussed was including an ascii-art map of the office space, which the current space design would allow. This feels a bit against the spirit of old-school text adventures, but seems like it could really help players. I'm thinking of something non-interactive in the inventory with labels like "O6" and "H4" -- not saying what is located where. What do you folks think (especially curious what @spacehobo thinks).

**Comment by pahp** [comment]
Some kind of ASCII map like this (maybe with room IDs?)
```
+----+------+--------+----+
|    |      |        |    |
|    |      |        |    |
|    +--#---+--#-----+    |
|    |               |    |
|    #   |       |   +--#-+     
+----+   |       |   #    |
|    |   +---+---+   |    |
|    #   |   |   |   +----+
|    |   #   |   #   |    |
+----+   |   |   |   #    |
|    #   +---+---+   |    |
|    |   |       |   |    |
+----+   |       |   +----+
|                    |    |
|                    #    |
+----+-----+-##-+----+----+
           |    |
           +----+
```

**Comment by spacehobo** [comment]
One thing that players need to comprehend is the way in which a "room" in the game's internal structures may not actually be what we think of as a "room" in the in-universe sense.  For example, stepping north behind the receptionist's desk doesn't *feel* like you're in a new room, even if it is walled off.

That said, there is a long tradition of providing "feelies" with Infocom games, sometimes as aids to play or as copy-protection elements.  We could produce a set of PDFs with items like a fire evacuation map for this floor, which would feel like a real object from the in-game world.  

There may be other objects that are inexpensive to produce with the resources of a University, which could help sell the illusion to students. I'd imagine it might not be too much trouble to screen-print custom keycards, or maybe there's some UMN tat from the student bookshop that we could include in the game or something.

**Comment by pahp** [comment]
I will make a fire escape plan "feelie" image that looks sufficiently retro and institutional that we can link and/or print. This map will include room names and a compass rose (or similar) on it to make it easier for players to orient themselves.

**Comment by pahp** [comment]
There is a map in the [Google Doc manual](https://docs.google.com/document/d/1Zygrv_E8scvrlbjES6tvPm9_EG7zzXPxoqeJySPHELA/edit?usp=sharing) and I have the SVG source for it. Eventually, the map and manual should probably be in the repository.
