### ISSUE TITLE
move verb broken

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#142]
testers tried "move [object]" which would display an error, but move the object to the player's inventory. This bypassed the weight limits as well (example: picking up the heavy chair while the heavy plant is in their inventory)

**Comment by pahp** [comment]
whoa, that's weird!

**Comment by spacehobo** [comment]
The `move` verb is normally an alias for `push`, `clear`, `press`, and `shift`. We seem to have aimed it at `transfer`, which seems overcomplicated when what we really want to do is to catch `push/move foo to bar` (which the built-in `transfer` verb supports). 

```
> move key

[** Programming error: tried to test "has" or "hasnt" of nothing **]

[** Programming error: nothing (object number 0)  has no property
before to send message **]

[The score has just gone up by 4 points.]
```

**Comment by spacehobo** [comment]
Put another way, this seems erroneous: https://github.com/UMDLARS/one_night_in_sf/blob/main/untitledHeistGame.inf#L99-L103

We may want to make it `* noun 'to' noun -> Transfer;` the way it is in the upstream library, and extend rather than replace.
