### ISSUE TITLE
plunge verb

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#147]
using the plunger it is natural to use "plunge" for the verb however this hasn't been implemented

**Comment by pahp** [comment]
... aaaaand this is why we playtest with real humans who were uninvolved with the design.

**Comment by spacehobo** [comment]
Do we want a humorous response saying you're not here for plumbing, or do we want it to work as the verb to solve the puzzle?  We could do both in different circumstances if you like.

**Comment by pahp** [comment]
How about you can plunge the toilet or the floor tile (with different messages of course), but anywhere else it says something like "Hmm, I don't see anything plungeable here." Maybe the humorous line about plumbing would be when you plunge the toilet, and it could say something like "Maybe there's something else in this office you could plunge..."
