### ISSUE TITLE
Flashlight has lamp name which prevents interacting with lamp while in lobby

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#150]

**Comment by pahp** [comment]
I wonder if I called it a lamp to be cheeky (per old Infocom games) or if it was something in how light sources work (e.g., they are always called lamps by default). I would suggest removing 'lamp' from the flashlight description if possible.

**Comment by spacehobo** [comment]
The short answer to this is that `held` objects gazump nearby objects when disambiguating.  You can see the full algorithm explained in pages 239-242 of the DM4.  We could probably hack around this with a custom `ChooseObjects` method, but that seems like more work than simply removing `lamp` from the torch's aliases.
