### ISSUE TITLE
some verbs (e.g., use) claim "you won't need to do anything with it" about important objects

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#163]
See title.

**Comment by pahp** [comment]
"use" may be an overly vague verb -- we don't want to just give them the right outcome because they knew the thing was "useful" in some way, but this kind of error is misleading.

**Comment by spacehobo** [comment]
This is a matter of going through and adding `instructions` properties like I did with the `ladder` and the `screwdriver`.  Once we fix #143, all this will become help text for the player.

**Comment by spacehobo** [comment]
Oh dang, sorry, that commit doesn't fix this one but rather #126.  My bad.

**Comment by spacehobo** [comment]
As penance, I am going through and adding instructions to more held objects.
