### ISSUE TITLE
parchment replaces certain character sequence (e.g., "ff", "fl") with unicode ligatures in user entry area

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#164]
Examples:
![image](https://github.com/UMDLARS/one_night_in_sf/assets/15266857/7d3c7c4f-6f6c-4a8e-92a3-7f1de05d99f8)
...
![image](https://github.com/UMDLARS/one_night_in_sf/assets/15266857/164d7acb-50b2-494a-b46c-465d37b8abc5)

**Comment by spacehobo** [comment]
Hmm, I have `font-variant-ligatures: none;` already in the CSS.  I wonder why it's not taking effect for you consistently.
