### ISSUE TITLE
Heavy object remains in inventory when thrown at glass wall

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#168]
![image](https://github.com/UMDLARS/one_night_in_sf/assets/116676184/22dab5f7-8dd4-41d7-a290-181306f069b5)

I'm not sure which way we'd want this however it seems to make sense that it would no longer be in your inventory. Nothing about the description says you retrieve the chair again.

**Comment by pahp** [comment]
Oooh, good one. Yeah, I would say that if you throw a heavy object it should end up in whatever room you are currently in (just to keep us from having to figure out whether it would be allowed to move into the next space, etc... it's heavy, it doesn't go far).
