### ISSUE TITLE
Update checklist if item is not in inventory

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#196]
Currently the checklist will still mark an item as retrieved once it has been touched but if you remove it from your inventory.

**Comment by spacehobo** [comment]
The task list actually formats the PunyInform task system's data, so the solution is to change when we call things like `Achieved(GET_BACKUP_TAPE);` or to have a second `EXFIL_BACKUP_TAPE` task numbered right after it.
