### ISSUE TITLE
can't finish the game with the test

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#217]
[I added a complete walkthrough (of all scored items) with this commit](https://github.com/UMDLARS/one_night_in_sf/commit/4fc8493f1428d9b94b377b345b05e5f73d70095c), but when I add `> s` to leave the Lobby back to the elevator to win, I get this outcome:

```
untitledHeistGame.out:2790:*** Exception: Timed out awaiting output
make: *** [Makefile:65: untitledHeistGame.out] Error 1
```

I suspect maybe the testing script doesn't know what to do when the game ends?

The current test case just ends in the Lobby with all scored items.

**Comment by spacehobo** [comment]
https://github.com/erkyrath/plotex/blob/master/regtest.py#L552-L558 ← Looks like it's looking for a `>` prompt explicitly, and when you win you get a prompt ending in `?`...

**Comment by pahp** [comment]
I took @spacehobo 's idea and had it run score and check for 131.
