### ISSUE TITLE
“remove pins” says “That wouldn’t be useful” even though the answer was really close

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#226]
Saying "remove pins" or "remove hinges" (or possibly other words) should give a hint like "remove them with what?" rather than just saying "That wouldn't be useful." 

I'm creating this as a separate issue because (in my understanding) fixing this error is different than just spamming synonyms/verbs.

**Comment by spacehobo** [comment]
```
Verb 'remove'
        * worn                                      -> Disrobe
        * multi                                     -> Take
        * multiinside 'from' noun                   -> Remove;
```

By default, trying to `remove` something that's in the room with you will invoke the `Take` verb.  You can solve this with a `before` hook on `Take`.

But from what I saw, this stuff has been moved to cheap_scenery, which may not be the best use of that system.  You lose a lot of behaviour if the objects are actually meant to be real things the player can interact with in complex ways.
