### ISSUE TITLE
Security Key at the beginning doesn't recognize "key" as synonym

### ISSUE THREAD

**Issue by SpaceWhaleSoft** [UMDLARS/one_night_in_sf#258]
It just works if you type "security". Key should be allowed for better player experience.
<img width="2124" alt="Screenshot 2024-09-19 alle 17 26 18" src="https://github.com/user-attachments/assets/25865883-16b0-482b-8fa3-ac3a30bb942e">

**Comment by pahp** [comment]
Thanks for this report! We'll look into getting it fixed.
