### ISSUE TITLE
Make key objects not be displayed seperately from description

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#26]
Currently objects that are implemented (i.e the ladder) are described in the room description but after it displays "Here you see [list of objects]" have this displayed in the description like all other objects/cheap scenery as to not stick out.

**Comment by spacehobo** [comment]
This can be trivially achieved with the `has concealed` attribute.  I believe we've already done this for the glass wall.  You need to take care that your room descriptions dynamically handle the case where you've moved, say, the ladder out of the room it was described in.

**Comment by spacehobo** [comment]
I tried marking objects as scenery/concealed, but I think it made for more UX problems than it solved (see #79 for an example).  My personal feeling is that it's not the worst thing if objects you can interact with get printed separately, as that's kind of a staple feature of modern IF. 

If this gives too much away for pedagogical purposes, we can work out specific exceptions, but it would take a lot of coding to make it fold in more naturally to room description paragraphs.  Perhaps this is worthwhile as a later bit of polish.

**Comment by Saturn-99** [comment]
Decided not an issue
