### ISSUE TITLE
Add more acceptable phrases

### ISSUE THREAD

**Issue by libraun** [UMDLARS/one_night_in_sf#266]
E.g., "insert fob into scanner" should also accept "show fob to scanner", "present fob to scanner", "scan fob (?)"

**Comment by pahp** [comment]
insert card into scanner
scan card
scan id
insert id into scanner
show id to scanner

**Comment by libraun** [comment]
![onisf_p2](https://github.com/user-attachments/assets/3688cda7-7085-4a6a-9d7f-e6ca3b3e394f)
![onisf_p1](https://github.com/user-attachments/assets/210917f2-6e9d-44b2-ae98-7709a473b66c)

Got the weirdest issue going on here. I think it has to do with manually changing position outside scope, but we don't have the OPTIONAL_MANUAL_SCOPE flag set, so (I think?) we can't do manual scope updates like this.

Not sure if it's a huge deal because it's not affecting the actual gameplay, but it feels unnatural.
