### ISSUE TITLE
Implement climb verb

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#27]
Implement the climb verb such that player can also use things such as "climb down" to move from the crawl space to "April's Office"

**Comment by spacehobo** [comment]
The re-implementation of the Crowther&Woods Adventure game (`advent.inf`) handles it like this:

```
Scenic  -> "pit"
  with  name 'pit' 'thirty' 'foot' 'thirty-foot',
        description "You'll have to climb down to find out anything more...",
        before [;
          Climb:
            MovePlayer(d_obj);
            rtrue;
        ];
```

Where `Scenic` is just a silly class they made that ensures the object `has scenery`. 90s OO, eh?
