### ISSUE TITLE
IT room floor tile needs help

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#38]
The IT room floor tile is currently a traditional locked door using the plunger as key.

Instead, it should work something like this:

> d
You are too big to fit through the cracks between the tiles. If only you could lift a tile up!

> lift tile
The spaces between the tiles are too small for your fingers. What do you want to lift the tile with?

> lift tile with plunger
You suction the plunger to a tile and lift it out of its place. 

(This should create a floor tile object on the floor of the room, AND modify the description of the room)

**Comment by spacehobo** [comment]
I think it should be fine for this to be done with dynamic descriptions.  Perhaps the tile could be a concealed door that does a `give self ~concealed` on being opened/unlocked?
