### ISSUE TITLE
inventory capacity management

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#41]
It might be nice if a player could only hold one heavy object at a time, and if a player cannot enter or pass through the raised flooring crawlspace with any large items. 

For example, if the player pulls out a floor tile, I love the idea that they take that tile and use it to break the glass window. But it seems really dumb if they can take up a floor tile but then crawl through a crawlspace with that tile in their inventory.

**Comment by spacehobo** [comment]
I suspect the trick here is to have something like the following in a `Before` hook for the various movement actions:

```
objectloop(x in player && x has heavy) "You couldn't possibly fit while carrying ", (the) x, "!";
```

Untested, so there may be some debugging to do to make this work.  Also I've inlined what is basically a `foreach(...) { ...}` kind of loop, so maybe you want to lay it out in a way that's less dense.

**Comment by spacehobo** [comment]
The DM4 has [the following](http://inform-fiction.org/manual/html/s50.html) to say on the topic of inventory capacity:

> ##### Capacity and exhaustion puzzles.
> 
>  Again, unpopular because their solution is normally tiresomely repetitive, forcing the player to keep putting things down and picking them up again. It can seem ridiculous that the protagonist can carry hundreds of bulky and fiddly things around all the time, so many designers impose a limit for realism's sake, typically of seven objects. It is bad form to set puzzles making life difficult because the limit is four and not five (after all, in emergency anyone can always carry one more item). In some games the limit is instead on total weight. Taking realism further, some games measure a state of health or even numerical levels of “strength” and “constitution” during play. The protagonist grows hungry and needs food, tired and needs sleep (in ‘Enchanter’ he is positively narcoleptic), wounded and needs recuperation. ‘Planetfall’ simulated a progressive illness whose symptoms are increasing need for food and sleep, and put many players off this kind of puzzle for life. Exhaustion rules are difficult to make fair. A rule requiring a return to an orchard for fruit should be watched carefully, as it will irritate a player to have to do this for a second, a third or a tenth time.

The floor tile is currently a "door", and should probably stay in the room where it lives.  It mostly just needs separate open/closed descriptions to make that work smoothly.  That should also handle the "you don't need to worry about this" hinting in the sense that you can't pick it up.  It may want a "you don't *need* to pick this up" error message, but it could also tell a tale about how difficult it would be to carry it around via the plunger.

I think we can try adding rules about bulky or heavy objects, but that should be polish for much later down the line, and we should be careful not to introduce needless chicken/fox/grain puzzles where they don't help the lesson.
