### ISSUE TITLE
Add additional aliases to objects with spaces in their name

### ISSUE THREAD

**Issue by Saturn-99** [UMDLARS/one_night_in_sf#54]
Coffee card and hard disk drive are two examples

**Comment by spacehobo** [comment]
I think we have done this simply by virtue of supporting the component nouns:

```
> s
(Kitchenette)
This is a kitchenette. To the north the room extends into the hallway.

You can see a Coffee Card here.

> get coffee card
Taken.
```

The drive currently supports `take hard drive` but doesn't have the word `disk` in it.  We're Z5 so we can do more than three dictionary words, so I'll just land that with some of the other little fixes I'm making in  PR #69
