### ISSUE TITLE
pick lock with card

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#71]
If you try to "pick lock with card", it won't work. Should it?
```
> pick lock with card
You can't see any such thing.
```

**Comment by spacehobo** [comment]
Are you picking the lock, or the latch of the door?  Is that an important distinction in this game?

**Comment by pahp** [comment]
So, I always envisioned it as pushing the latch from behind with a credit card. So technically, not picking the lock. But I think that might be language that people would use to describe what you're doing because your bypassing the "lock". Incidentally, I think it would be harder to use a flathead screwdriver to do this then a credit card. And, I like the idea of each door being opened by a different method.

**Comment by spacehobo** [comment]
OK, we can try to support that syntax, to be sure, but we should carefully describe what's actually happening when it works.  

And we should also be prepared to give a reason *why* the screwdriver won't work, when someone tries it.  Give them a hint that they need something *thinner*.

**Comment by pahp** [comment]
Yeah. Precisely! I agree 100%.
