### ISSUE TITLE
ellie's hard drive has an awkward name

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#73]
When you open the computer in Ellie's Office, you see this:

> You can see a Office Door, a Desk and a Computer (which contains **a Ellie's Hard Drive**) here.

(emphasis added)

Suggest renaming it something unique but that will facilitate grammar, like "silver hard drive" or something.

**Comment by spacehobo** [comment]
If we gave it `has proper`, then the game would understand that "Ellie's Hard Drive" is a proper noun.  It then would treat it as a unique identifier and never try to print articles in front of it.

Do you think that's better or worse than giving it a more generic name?
