### ISSUE TITLE
a tale of two screwdrivers

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#75]
There could be two screwdrivers, a "phillips" (plus) screwdriver for the case, and a "flathead" screwdriver for the hinge bolts? Maybe the phillips would be in the IT office?

**Comment by spacehobo** [comment]
I'd make the flathead harder to find, and it should probably work as the tool for the door that can be opened with the card.

**Comment by pahp** [comment]
The way I envision this, it would be hard to do this with the screwdriver. See the comment on the pick the lock with the card issue. Perhaps if you try it with the screwdriver it tells you it's a little too thick.

**Comment by pahp** [comment]
See #74 for some commentary on this. My favorite idea so far is the flathead is under a tarp with some paint cans in the spare office. This makes it a little tricky without making any puzzle dependencies, which I have been trying to avoid.

**Comment by spacehobo** [comment]
That's a good one!  I should also note that the word "Flathead" has some relevance in Zork lore.  I was thinking it should have a `NOT TO BE REMOVED FROM FLOOD CONTROL DAM #3` admonition carved into it.

**Comment by pahp** [comment]
Yes, I also thought about the Flathead reference! We should capitalize the F in Flathead, it will look like a typo but not be -- love the Flood Control Dam reference too.

**Comment by pahp** [comment]
April -- three items:

1.  can you please make sure the screwdriver's name is "Flathead" (capital F), and 
2. add the inscription above to the description of the screwdriver, and
3. make sure the two screwdrivers are easily distinguishable

Then we can close this one.
