### ISSUE TITLE
Add scores to objects and rooms

### ISSUE THREAD

**Issue by spacehobo** [UMDLARS/one_night_in_sf#78]
We have the score printed in the status line, but none of the objects or rooms thus far have been given a score.  The `Your score has just gone up` messages are an important signal to players that they're on the right track, so we should probably start adding `has scored` to the objects and places that lead a player forward.

**Comment by pahp** [comment]
Yeah! I love that. I think that every space is going to have some purpose, so giving a score to each space and important objects will be helpful and hopefully motivating.
