### ISSUE TITLE
Make openable desk drawer in receptionist area.

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#8]

**Comment by spacehobo** [comment]
I think this is a pretty traditional feature, and is mostly a matter of making something `has static container openable`.

Containers can also hook into `Receive` and `LetGo` actions as objects are placed into or removed from them.

**Comment by spacehobo** [comment]
It's probably best to cheese the desk and its drawer a little, and only make the one object that presents this state of affairs through description logic.
