### ISSUE TITLE
completion checklist inventory item

### ISSUE THREAD

**Issue by pahp** [UMDLARS/one_night_in_sf#84]
I had thought there as an issue for this before, but it seems like I was mistaken.

Anyway, I think the player should start with an item in their inventory (perhaps "checklist") that lists the items they need to steal. Each time they acquire one, it should be "checked" on the list, perhaps like:

```
Ellie's hard drive (in inventory)
```

...or somesuch.

I think the player should need to be holding all the items to win, so maybe each item in the checklist has three possible states:

 1. default -- not found
 2. found -- but not currently held
 3. held

... e.g.:

```
Ellie's hard drive (in inventory)
IBM 5100 (found but not in inventory)
Backup Tape (not found)
```

I think this kind of mechanism will be helpful and motivation for players, because it's kind of like a helpful todo list and achievement

**Comment by spacehobo** [comment]
Isn't this #81?
