### ISSUE TITLE
Scores indicate "has once picked up" rather than actual exfiltration

### ISSUE THREAD

**Issue by spacehobo** [UMDLARS/one_night_in_sf#88]
As I mentioned in #81, we grant scores the moment a player picks up a "treasure" object.  Really the goal here should be about *exfiltration* of data, so if there's a USB stick that causes a system to upload data to a drop site, it should count.  But generally we should have some equivalent of the Zork "Trophy Case" that the players have to get the various pieces of physical media to.  We can then  grant nominal `scored` object points when the player picks it up, and the high-value score when it's properly exfiltrated.

**Comment by pahp** [comment]
One solution to this would be for the janitor to have a "cart" in the lobby where they stash the items. When they head south to leave at the end, the message could say that you wheel the cart out of the office. If they otherwise try to move the cart, it should just say something like "no need to move the cart until you leave" or something.

**Comment by spacehobo** [comment]
One important thing to think about this is that the role of the score is partly a "you're on the right track" hint system.  If picking up a loose bottlecap gives you points, then you as the player suspect that it's important to the story.

**Comment by pahp** [comment]
Yeah, i think small points for taking something useful, and big points for putting it in/on the cart. Maybe even single digit points for useful objects, double digit points for taking something that's on the checklist, triple digit points for putting it on the cart (or something like that).

**Comment by spacehobo** [comment]
So the solution I went with in #198 was to forfeit *only* the task-granted points when the player drops a critical item, and let them re-gain the points if they pick it back up again.  The initial 4 points for finding a scored object in the first place remain.

I think we can remove score from objects that have more important tasks, and use the 4 point scores on tools that are part of the solutions to the game puzzles only.  We might calculate what score could be achieved by picking things up without solving puzzles, and give that a title of shoplifter or something.

**Comment by pahp** [comment]
I agree about only forfeiting points for the trophy items.

> I think we can remove score from objects that have more important tasks, and use the 4 point scores on tools that are part of the solutions to the game puzzles only.

I'm having trouble parsing this sentence. What is an example of an object that has a more important task (but is not a tool that is part of a puzzle)?

**Comment by Saturn-99** [comment]
Is there a reason this issue is still open? It seems resolved.

**Comment by spacehobo** [comment]
Agreed.  I'll close this now.
